# Generated by Django 3.2.7 on 2021-09-22 10:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('availabe_quality', models.IntegerField()),
                ('max_days_available', models.IntegerField(default=1)),
                ('department', models.CharField(choices=[('education', 'Education'), ('computer science', 'Computer Science'), ('mathematics', 'Mathematics'), ('engineering', 'Engineering')], default='Education', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2021, 9, 23, 10, 35, 51, 804321, tzinfo=utc))),
                ('issued_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanager.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
