# Generated by Django 3.2.7 on 2021-09-23 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0002_auto_20210923_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='availabe_quantity',
            new_name='available_quantity',
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 5, 38, 43, 299713, tzinfo=utc)),
        ),
    ]
