# Generated by Django 3.2.7 on 2021-09-23 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0003_auto_20210923_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 6, 9, 15, 368111, tzinfo=utc)),
        ),
    ]
