# Generated by Django 3.2.7 on 2021-09-24 03:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmanager', '0004_auto_20210923_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2021, 9, 25, 3, 50, 30, 809210, tzinfo=utc))),
                ('returned_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('returned', 'Returned')], default='returned', max_length=50)),
                ('reserved_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanager.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='IssuedBook',
        ),
    ]
