# Generated by Django 3.2.7 on 2021-09-24 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0005_auto_20210924_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedbook',
            name='IS_BookNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 6, 48, 28, 398792, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 6, 48, 28, 398792, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='status',
            field=models.CharField(choices=[('collection pending', 'Collection Pending'), ('outstanding', 'Outstanding'), ('returned', 'Returned'), ('return pending', 'Return Pending')], default='returned', max_length=50),
        ),
    ]
