# Generated by Django 3.2.7 on 2021-10-01 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0006_auto_20210924_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 16, 34, 24, 219231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 16, 34, 24, 219231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='status',
            field=models.CharField(choices=[('collection pending', 'Collection Pending'), ('outstanding', 'Outstanding'), ('returned', 'Returned'), ('return pending', 'Return Pending')], default='outstanding', max_length=50),
        ),
    ]
