# Generated by Django 3.2.7 on 2021-10-03 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0008_auto_20211002_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 5, 36, 58, 380826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 5, 36, 58, 380826, tzinfo=utc)),
        ),
    ]
