# Generated by Django 3.2.7 on 2021-10-11 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0010_auto_20211005_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 2, 6, 35, 180572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 2, 6, 35, 180572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='status',
            field=models.CharField(choices=[('Collection Pending', 'Collection Pending'), ('Outstanding', 'Outstanding'), ('Returned', 'Returned'), ('Return Pending', 'Return Pending')], default='outstanding', max_length=50),
        ),
    ]
