# Generated by Django 3.2.7 on 2021-10-11 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0011_auto_20211011_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='department',
            field=models.CharField(choices=[('Education', 'Education'), ('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Engineering', 'Engineering')], default='Education', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='IS_BookNumber',
            field=models.CharField(default='qrcode', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 9, 25, 2, 890433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 9, 25, 2, 890433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='status',
            field=models.CharField(choices=[('Collection Pending', 'Collection Pending'), ('Outstanding', 'Outstanding'), ('Returned', 'Returned'), ('Return Pending', 'Return Pending')], default='Collection Pending', max_length=50),
        ),
    ]
