# Generated by Django 3.2.7 on 2021-10-11 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0012_auto_20211011_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 9, 47, 29, 51577, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 9, 47, 29, 51577, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedbook',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Returned', 'Returned')], default='Reserved', max_length=50),
        ),
    ]
